require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/micropost_ranges", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MicropostRange. As you add validations to MicropostRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MicropostRange.create! valid_attributes
      get micropost_ranges_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      micropost_range = MicropostRange.create! valid_attributes
      get micropost_range_url(micropost_range)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_micropost_range_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      micropost_range = MicropostRange.create! valid_attributes
      get edit_micropost_range_url(micropost_range)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MicropostRange" do
        expect {
          post micropost_ranges_url, params: { micropost_range: valid_attributes }
        }.to change(MicropostRange, :count).by(1)
      end

      it "redirects to the created micropost_range" do
        post micropost_ranges_url, params: { micropost_range: valid_attributes }
        expect(response).to redirect_to(micropost_range_url(MicropostRange.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MicropostRange" do
        expect {
          post micropost_ranges_url, params: { micropost_range: invalid_attributes }
        }.to change(MicropostRange, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post micropost_ranges_url, params: { micropost_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested micropost_range" do
        micropost_range = MicropostRange.create! valid_attributes
        patch micropost_range_url(micropost_range), params: { micropost_range: new_attributes }
        micropost_range.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the micropost_range" do
        micropost_range = MicropostRange.create! valid_attributes
        patch micropost_range_url(micropost_range), params: { micropost_range: new_attributes }
        micropost_range.reload
        expect(response).to redirect_to(micropost_range_url(micropost_range))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        micropost_range = MicropostRange.create! valid_attributes
        patch micropost_range_url(micropost_range), params: { micropost_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested micropost_range" do
      micropost_range = MicropostRange.create! valid_attributes
      expect {
        delete micropost_range_url(micropost_range)
      }.to change(MicropostRange, :count).by(-1)
    end

    it "redirects to the micropost_ranges list" do
      micropost_range = MicropostRange.create! valid_attributes
      delete micropost_range_url(micropost_range)
      expect(response).to redirect_to(micropost_ranges_url)
    end
  end
end
